schema_version: 1

context:
  name: param-sweeps
  version: 0.3.0a1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: 51e51c36d20fab27e3bb4a91c0a53bcbb0568f3fbf79fb9cf967db5bf665371d
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10.0,<4
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=3.10.0,<4
    - numpy >=1.26.0,<1.27.0
    - geoh5py >=0.10.0b1,<0.11.0a.dev

tests:
  - python:
      imports:
        - param_sweeps
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: A Parameter sweeper for applications driven by ui.json files.
  description: |
    The param-sweeps library contains two main modules. One is for generating sweep files,
    and the other is to run a sweep over some number of parameters in a driver application.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/param-sweeps

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
